# Issues

## Jason

1. On line 825, when I run the tests, I get the following error:

    ```
    rest_framework.exceptions.ValidationError: {'rider': {'username': ['A user with that username already exists.']}}
    ```

1. You often put the explanation before the code block which can be confusing when you reference the code in the explanation. I will move the explanations around, but just be mindful of this in the future, as you write the client-side.

## Michael

1. rename apps to `taxi` and `trip`
1. add final deployed app
1. add failing test trace
